music/urls.py
from django.conf.urls import url
from . import views

app_name='music'
urlpatterns =[
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),

    # /music/213/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailsView.as_view(), name='detail'),

    ## /music/album/add
     url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add'),

]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from django.db import models
from django.urls import reverse




class Album(models.Model):
    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=100)


    def __str__(self):
        return self.album_title

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk': self.pk})


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_tilte = models.CharField(max_length=100)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_tilte

music/views.py
from django.views import generic
from .models import Album
from  django.views.generic.edit import  CreateView,UpdateView,DeleteView
from django.core.urlresolvers import reverse_lazy


class IndexView(generic.ListView):
    template_name = 'music/index.html'
    context_object_name = "all"




    def get_queryset(self):
        return  Album.objects.all()



class DetailsView(generic.DetailView):
    model=Album
    template_name = 'music/details.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']


class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']


class Albumdelete(DeleteView):
    model = Album
    fields = ['artist','album_title','genre','album_logo']

music/templates/music/album_form.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block albums_active %}active{% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                         {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block title %}Nikhil Song App{% endblock %}</title>

<!--  load the path-->
{% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Satisfy" type="text/css">


</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- logo -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target='#topNavBar'>
            <span class ="icon-bar"> </span>
            <span class ="icon-bar"> </span>
            <span class ="icon-bar"> </span>
            </button>
            <a class ="navbar-brand" href="{% url 'music:index' %}">Nikhil Django Song App</a>
        </div>

        <!-- items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class ="nav navbar-nav">
                <li class="active">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon  glyphicon-cd " aria-hidden="true'"></span>&nbsp;
                        Album
                    </a>
                </li>

                <li class="">
                    <a href="{% url 'music:index' %}">
                        <span class="glyphicon  glyphicon-music " aria-hidden="true'"></span>&nbsp;
                        Songs
                    </a>
                </li>
            </ul>

            <form class ="navbar-form navbar-left" role="search" method="get" action="#">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="">
                </div>
                <button type="submit" class="btn btn-default">Search</button>

            </form>
          <ul class ="nav navbar-nav nav-right">
              <li class="">
               <a href="{%url 'music:album-add' %}">
                        <span class="glyphicon  glyphicon-plus " aria-hidden="true'"></span>&nbsp;
                        Add Album
                    </a>
              </li>
              <li class="">
               <a href="#">
                        <span class="glyphicon  glyphicon-off " aria-hidden="true'"></span>&nbsp;
                        Log Out
                    </a>
              </li>




        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/details.html
{% extends  'music/base.html' %}
{%block title %}Song Detail Page{% endblock %}
{% block body  %}
<img src="{{ album.album_logo }}" style="width: 250px;">

<h1>{{ album.album_title }}</h1>
<h3> {{ album.artist }}</h3>


  {% for song in album.song_set.all %}
          {{song.song_tilte}}
          {% if song.is_favorite %}
              <!--img src="http://desssign.com/images/youtube-logo.png"-->
          {% endif %}
          <br>
  {% endfor %}



{% endblock %}

music/templates/music/favorite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_tilte">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends  'music/base.html' %}
{%block title %} App HOME{% endblock %}
{% block body  %}

<ul>
    {% for album in all  %}
    <li><a href="{% url 'music:detail' album.id %}">{{ album.artist }}</a></li>
    {% endfor %}
</ul>
<ul>

</ul>

{% endblock %}